# Generated by Django 5.0.7 on 2024-07-26 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_tweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retweets', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('replies', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tweet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to='upload.tweet')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
