# Generated by Django 5.0.7 on 2024-07-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_instagramcredentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramcredentials',
            name='user',
        ),
    ]
