# Generated by Django 5.0.7 on 2024-08-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='status_change_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
