# Generated by Django 5.0.7 on 2024-08-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_image_status_change_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status_change_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status_change_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
