# Generated by Django 5.0.7 on 2024-08-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0012_alter_link_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_add_image', 'Can add image'), ('can_add_document', 'Can add document'), ('can_add_post', 'Can add post'), ('can_add_video', 'Can add video')]},
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
