# Generated by Django 5.0.7 on 2024-08-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0013_alter_user_options_user_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OnlyEvent',
            new_name='Event',
        ),
        migrations.AlterField(
            model_name='content',
            name='end_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='momrow',
            name='comments_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='momrow',
            name='completion_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='momrow',
            name='contributors',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='momrow',
            name='decision_taken',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='momrow',
            name='discussion_lead',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='momrow',
            name='discussion_points',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='momrow',
            name='impact',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='momrow',
            name='priority_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='momrow',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='momrow',
            name='tentative_dates',
            field=models.TextField(blank=True),
        ),
    ]
