# Generated by Django 5.0.7 on 2024-08-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0014_rename_onlyevent_event_alter_content_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
