# Generated by Django 5.1 on 2024-08-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0017_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momrow',
            name='action_items',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='momrow',
            name='follow_up_required',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
