# Generated by Django 5.1 on 2024-08-26 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0018_alter_momrow_action_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_departments', to='upload.department'),
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='upload.department')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='divisions',
            field=models.ManyToManyField(blank=True, related_name='users', to='upload.division'),
        ),
        migrations.CreateModel(
            name='SubDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='upload.division')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='subdivisions',
            field=models.ManyToManyField(blank=True, related_name='users', to='upload.subdivision'),
        ),
    ]
