# Generated by Django 5.1 on 2024-08-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0019_department_parent_division_user_divisions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='divisions',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='upload.division'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subdivisions',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='upload.subdivision'),
        ),
    ]
