# Generated by Django 5.0.3 on 2024-09-09 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0022_message_edited_message_read_message_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.division'),
        ),
        migrations.AddField(
            model_name='content',
            name='subdivision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.subdivision'),
        ),
        migrations.AddField(
            model_name='document',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.division'),
        ),
        migrations.AddField(
            model_name='document',
            name='subdivision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.subdivision'),
        ),
        migrations.AddField(
            model_name='event',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.division'),
        ),
        migrations.AddField(
            model_name='event',
            name='subdivision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.subdivision'),
        ),
        migrations.AddField(
            model_name='image',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.division'),
        ),
        migrations.AddField(
            model_name='image',
            name='subdivision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.subdivision'),
        ),
        migrations.AddField(
            model_name='link',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.division'),
        ),
        migrations.AddField(
            model_name='link',
            name='subdivision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.subdivision'),
        ),
        migrations.AddField(
            model_name='post',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.division'),
        ),
        migrations.AddField(
            model_name='post',
            name='subdivision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.subdivision'),
        ),
        migrations.AddField(
            model_name='video',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.division'),
        ),
        migrations.AddField(
            model_name='video',
            name='subdivision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.subdivision'),
        ),
    ]
