# Generated by Django 5.0.3 on 2024-09-17 12:59

import upload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0026_ticket_ticketupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to=upload.models.name_file, verbose_name='Ticket Attachment'),
        ),
    ]